### PR TITLE
Add endpoint to config.

### PR DESCRIPTION
**Pull request by cgroschupp**
Allow to specify the endpoint, to use with minio or other s3 compatible endpoints.

### CODE REVIEW

**Comment by cgroschupp** [comment]
cla recheck

**Comment by cgroschupp** [comment]
@jsvd Are there any suggestions for improvement?

**Comment by cgroschupp** [comment]
@ph Can you look at this pr?

**Comment by mbarretta** [comment]
@jsvd with this merged, is it a solid target for 6.3 release?

**Comment by jsvd** [comment]
Certainly!

**Pull request merged**
