### PR TITLE
Enable proxy for assume role

### PR DESCRIPTION
**Pull request by wernerb**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

Solves https://github.com/logstash-plugins/logstash-mixin-aws/issues/40

### CODE REVIEW

**Comment by kares** [comment]
makes sense, could you maybe add a changelog entry and bump the version to `4.3.1`

**Comment by wernerb** [comment]
@kares i have bumped version and added changelog entry

**Comment by kares** [comment]
Thanks Werner, we still need a version [bump](https://github.com/logstash-plugins/logstash-mixin-aws/blob/master/logstash-mixin-aws.gemspec#L3)

**Comment by wernerb** [comment]
@kares done!

**Comment by wernerb** [comment]
Hi @kares is there a chance this can get merged?

**Comment by kares** [comment]
Hey Werner, sorry I never got back to this (:bell: :bank:rupcy). 
In the mean time I ended up rewriting bits to also resolve credentials issue with assume role.
It's tested with S3 and some tests: https://github.com/logstash-plugins/logstash-mixin-aws/pull/48

**Comment by wernerb** [comment]
That's great! Please close this then when your other PR is merged!

**Pull request closed without merging**
