### PR TITLE
Minor config validation fixes

### PR DESCRIPTION
**Pull request by jakelandis**
I did a quick search across the aws plugins and this config seems is pretty well encapsulated here, so I don't expect any issues with this change.  Perhaps a couple specs will need to be updated, which I will double check and fix if needed.

### CODE REVIEW

**Comment by danhermann** [comment]
Changes LGTM assuming the builds pass.

**Comment by jakelandis** [comment]
@danhermann - thanks.  The build failures are un-related, but I will look into fixing them.  Likely a different PR.

**Comment by jakelandis** [comment]
@danhermann - actually, i was missing a change to a file. would you mind taking another look ?

**Comment by jakelandis** [comment]
Confirmed that all the tests pass with the changes to the mixin for the following known plugins:

- [x] Input S3
- [x] Output S3
- [x] Input sqs
- [x] Output sqs
- [x] Input cloud watch
- [x] Output cloud watch
- [x] Output sns

**Comment by danhermann** [comment]
LGTM

**Pull request closed without merging**
