### PR TITLE
Added "eu-central-1" (Frankfurt, EU) to region validation

### PR DESCRIPTION
**Pull request by JohannesEH**

### CODE REVIEW

**Comment by purbon** [comment]
LGTM

**Comment by purbon** [comment]
@ph review?

**Comment by dwagner2301** [comment]
@purbon question: Why does this pull request look good to you and the request (#09) I submitted two days ago does not (which fixes the same issue)? It's not like tha I'm proud about that fix or anything like that. It's more like, that I'd like to know what's wrong with my PR so that I can avoid to make mistakes with future PRs.

**Comment by purbon** [comment]
@dwagner2301 I did not saw your PR I apologies, but yeah! both solve the same issue. Booths PR are doing the same.

**Comment by JohannesEH** [comment]
I'll close this PR then. @dwagner2301 didn't see your PR either. I guess great minds think alike. ;) Enjoy your weekend!

**Pull request closed without merging**
